### PR TITLE
Add Galician language

### PR DESCRIPTION
**Pull request by frandieguez**
Please consider adding these changes to have Cozy in Galician language

### CODE REVIEW

**Comment by geigi** [comment]
Are you still interrested in providing a translation for Galician on Transifex? If you need help let me know. Otherwise I'm going to close this PR...

**Comment by frandieguez** [comment]
Hi. I already have an account in transifex. 

I´ve just joined the translation group. Please get translations from this PR to not lose them.

Thanks in advance

**Comment by geigi** [comment]
Cool! ☺️ I've just uploaded your translations from this PR. Thanks for contributing! There are already some new strings.

**Comment by frandieguez** [comment]
all translations completed in transifex

**Comment by geigi** [comment]
Fantastic, thanks :)

**Pull request closed without merging**
