### PR TITLE
Show total time and time reading for books

### PR DESCRIPTION
**Pull request by oleg-krv**
Made a display of the total duration of books and the current position for books in the library and in the player.
I apologize for the many patches - but this is one of the useful properties of the audiobook player for me.
This is the initial implementation - the graphic design for the player can be done later.

### CODE REVIEW

**Comment by geigi** [comment]
Awesome! I will have a look at this tomorrow ;)

**Comment by oleg-krv** [comment]
The patch does not implement the installation of the acceleration / deceleration of the book - all the time is taken from the files, but when reading it is taken from the player, so we still need to think about how to make a correct calculation of the remainder before the book is completed...

**Comment by geigi** [comment]
I've just tested your code it works great so far.  
Some thoughts on the calculation implementation from the player:
- Every time a track changes an event gets called in the ui. There we could calculate the duration of all the previous tracks and save it. Have a look at the event handler `track_changed`.
- There is an event which updates the ui adapted to the playbackspeed. The event handler is in `__update_time`. Here we could add the previously calculated value to the position of the current track and display it in the ui.

Do you want to adapt your code into these systems?

I like the idea of the feature a lot and I have some thoughts on the ui side:
- There is a feature request that the slider is used for the whole book instead of the current track only. We could use your calculation for this and display it in the titlebar as the remaining time #53
- How about displaying a small percentage text above or a progressbar beneath each book cover (maybe not the nicest solution)
- Or how about displaying the percentage and remaining/whole duration of the book in the track popover at the bottom (my favourite)

**Comment by geigi** [comment]
Idea for the remaining time: I think we can just do ‘remaining_time/current_playback_speed‘ to get the correct remaining time

**Comment by oleg-krv** [comment]
Ok. I'll do the optimization by code today.
Concerning the idea of a common slider:
- in the player you have to make two sliders:
1) to display the fading position in the readable file - the current version
2) to display the general progress - without the possibility of a transition. The transition is more convenient to do on the button and in the pop-up window: by percentage or by time relative to the beginning of the book. This function is not very often called and will not clutter the interface.
In the library, you need to bring all the thumbnails to the same size with an additional background different from the background of the window: then you can make a vertical progress bar on the edge of the thumbnail - this will be very noticeable.

I have a question - how is the already-read 100% book indicated in the database?

And another idea - to break up the books into categories:
1) new - no reading has been started
2) the reading is started
3) read 98% or more

Conveniently implemented in the program for Android Smart AudioBook Player
https://play.google.com/store/apps/details?id=ak.alizandro.smartaudiobookplayer

**Comment by oleg-krv** [comment]
Very approximate outlines of the library, sketched in the code. If approved, I will design it as a patch. The design of the cover of the book is given by the image. I did not change the style of the progress bar display - then it will be possible to change the style of the cover.
I'm still just learning programming in python with gtk :)
image

**Comment by geigi** [comment]
I have a question about the two silders: Where do you thought the slider would be positioned? Beneath the existing one? So they'll be visible at the same time (in the title bar)?

Currently an already read book is reset to not listened, so there isn't a 100% stage currently. But this should be implemented when cozy displays the percentage. Propably it will be that the book position points to the last track and the track position in the db is at the very end. So it'll be implicitly saved that the book is finished.

I like the idea about sorting the books with the reading status! I'm including this to my todo list ;)

I also like the idea of what you did with the book covers. Although I would go for a more modern and minimalistic design because that was my intention with Cozy. It should feel as clean and look good as if the application was from the gnome team itself. But I'm not sure yet what the best way to display this is. What about: the percentage as text in the bottom right corner of the book and a checkmark if you finished it?

**Comment by oleg-krv** [comment]
Ok I'll try to make the option "display books in the library" in the settings where it will be possible to choose the display type:
1) clean book - current book view
2) dark gray book
image
3) light gray book
 image
Ok?

**Comment by geigi** [comment]
I would prefer a much cleaner look for example with a simple progressbar on the bottom like on the Amazon Kindle: https://juliankay.com/wp-content/uploads/2012/12/kindle-home.jpg
I think the 3d book view looks a bit out of place when compared to other Gnome applications and that's the look I also want for cozy. So I think I will not merge this view for now, but if you have another idea let me know :)
I'll also create some gui mockups

**Comment by oleg-krv** [comment]
I changed the processing to display the time for reading books.
The display of the current time was left tied to the slider - since it is necessary to recalculate% of the reads from the book.
display in the library - I'll think about how else to do it

**Comment by oleg-krv** [comment]
Yesterday I drew the following mapping in the code:
image
This template for displaying the book will you go?

**Comment by geigi** [comment]
This looks pretty nice! Maybe we could display the time as "10h 51min" to create a cleaner look? Maybe we could display the remaining time in there for books that are not at 0%?

**Comment by oleg-krv** [comment]
update cover book.
how do you like this player design?
image

**Comment by geigi** [comment]
Sorry for the late answer :)

I think the title bar is already quite full and with your additions it looks very tall and a bit untidy. I think the best way of including this functionality into the titlebar is by using the already existing widgets to preserve the usability. We could display the remaining time of the book instead of the remaining time for the track (changable by the user). 

I also thought about how to display it in the library and I think the most elegant way is to put it in the popover for the book. If the user wants to check his progress he can do this easily. For the current book he can check it in the titlebar and the library overview remains clean.

Here is a mockup I made: 
screenshot from 2018-02-11 14-14-44
I'll have a look at all of you code in the pull request today to implement this :)

**Comment by geigi** [comment]
I've impemented this feature now with only very little of ui changes. You can check it out on the master branch :) I've still used some of your code so thanks a lot for that!

**Pull request closed without merging**
