### PR TITLE
Use uniform gaps in book grid

### LINKED ISSUE #637: Huge grid gaps
The current grid layout looks pretty broken at many window sizes, because the gaps between cards are huge:

cozy-grid2

Ideally the spacing between and around columns should be fixed (probably 12px), and their size should dynamically change to fill the entire width given the current number of cards that can fit with the minimum card size.

I've also noticed that some cards are wider than the rest (I assume due to the title string?), which probably contributes to the column gap issue.

### System Information
- Operating System: Fedora 34
- Installation source: Flathub
- Version of cozy: 1.1.2

### PR DESCRIPTION
**Pull request by rdbende**
Fixes #637

### CODE REVIEW

**Comment by grahamvh** [comment]
approve,
I can't seem to reproduce the mentioned bug (I don't see a difference on my laptop of phone running master vs this branch). If it helps, I have no objections though.
Otherwise:
* Looks very strait forward
* No issues on mobile or desktop that I see

**Review by grahamvh — APPROVED** [review]
Approve

**Comment by rdbende** [comment]
> I can't seem to reproduce the mentioned bug

It was mostly a problem in the GTK3 version, in the current master it's much better. The only thing really this fixes is where the gaps weren't uniform on every side.

**Comment by geigi** [comment]
Looks good to me but it looks like we have a conflict with the current master sadly

**Review by geigi — APPROVED** [review]

**Comment by geigi** [comment]
Should we stick to the `Flowbox` with this PR?

**Comment by rdbende** [comment]
> Should we stick to the `Flowbox` with this PR?

Yes, for now, I think we should. The port to `GridView` will probably be a bigger rework.

**Comment by rdbende** [comment]
> Looks good to me but it looks like we have a conflict with the current master sadly

Yeah, that's why I tend to avoid having too many open PRs at once. That said, bow that many of them are merged there's more to come 😄

Anyway, the conflict resolution looks good to me as well. Can you merge it? Sadly I can't, because for that Github needs an approving review on the latest commit from someone other than the PR author.

**Pull request merged**
