### PR TITLE
Update Pypi dependencies for Flatpak/GNOME Builder

### PR DESCRIPTION
**Pull request by rdbende**

### CODE REVIEW

**Comment by rdbende** [comment]
This breaks the whatsnewdialog again though, as something was changed in `packaging`

**Comment by rdbende** [comment]
So `packaging.LegacyVersion` was removed in v22.0 (released on 7. December 2022), therefore the code in `whats_new_window.py` doesn't work.

Personally, I'd drop these dialogs altogether, as they are no longer relevant, and it's not great UX nonetheless to have a dialog pop up with every new feature. Instead, release notes are displayed in the app center and in the about dialog under the "What's New?" section (#806), and we can advertise new features on TWIG and Mastodon.

**Comment by rdbende** [comment]
Ahh, and these also need to be updated in https://github.com/flathub/com.github.geigi.cozy

**Comment by geigi** [comment]
Yes I think we can drop the whats new windows :)

**Comment by rdbende** [comment]
Depends on #832, so marked as draft.

**Comment by rdbende** [comment]
To be merged after #832

**Pull request merged**
