### PR TITLE
Update translations + French translations

### LINKED ISSUE #148: Add appdata to be translated
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi! Finally translations are here and working correctly! I tried to build the app and this is working well :smile: This will close #148.

# Changelog
- Update translations files (add missing translation strings)
- Separate extra translations files from main translations (`appdata` and `desktop`)
- Fix some deprecation
- Add existing translations back
- Update French translations
- Add extra French translations
- Replace ... typo by … as recommended by elementary
- Fix "elementaryOS" typo. This should be written with a space: "elementary OS"

You'll probably have to deal with Transifex to make these new files compliant. Let me know if you have some questions.

**This PR is ready for review**

### CODE REVIEW

**Comment by geigi** [comment]
Hey :) Thanks for the pull request, I appreciate your work! Since you changed quite a lot I'll do some testing before merging (especially with transifex because I'll have to change the teams etc.  Also I have to test building the packages for flatpak and other distributions which should take several hours of work). 

Two small things from my side:

Altough you suggested otherwise (and I understand your point) could you remove the empty language files again? I double checked and this is not integrating well with the cozy translation workflow. Almost all cozy translators use transifex and therefore it has to work primarily on there. Otherwise I would need to do this myself as languages on transifex are added only on demand.

The elementaryOS build process is failing. Somethings wrong with `meson_post_install.py`. Here is the log:

```
I: Building the package
I: Running cd /build/com.github.geigi.cozy-0.0.1/ && env PATH="/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin" HOME="/nonexistent" dpkg-buildpackage -us -uc -rfakeroot
dpkg-buildpackage: info: source package com.github.geigi.cozy
dpkg-buildpackage: info: source version 0.0.1
dpkg-buildpackage: info: source distribution juno
dpkg-buildpackage: info: source changed by Rabbitbot <developer@elementary.io>
 dpkg-source --before-build com.github.geigi.cozy-0.0.1
dpkg-buildpackage: info: host architecture amd64
dpkg-source: warning: unknown information field 'Standards-Version' in input data in package's section of control info file
 fakeroot debian/rules clean
dh clean 
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/build/com.github.geigi.cozy-0.0.1'
rm -rf debian/build
make[1]: Leaving directory '/build/com.github.geigi.cozy-0.0.1'
   dh_clean
 dpkg-source -b com.github.geigi.cozy-0.0.1
dpkg-source: warning: unknown information field 'Standards-Version' in input data in package's section of control info file
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building com.github.geigi.cozy in com.github.geigi.cozy_0.0.1.tar.xz
dpkg-source: warning: missing information for output field Standards-Version
dpkg-source: info: building com.github.geigi.cozy in com.github.geigi.cozy_0.0.1.dsc
 debian/rules build
dh build 
   dh_update_autotools_config
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/build/com.github.geigi.cozy-0.0.1'
mkdir -p debian/build
cd debian/build && meson --prefix=/usr ../..
The Meson build system
Version: 0.49.2
Source dir: /build/com.github.geigi.cozy-0.0.1
Build dir: /build/com.github.geigi.cozy-0.0.1/debian/build
Build type: native build
Project name: com.github.geigi.cozy
Project version: 0.6.7
Build machine cpu family: x86_64
Build machine cpu: x86_64
Message: Looking for dependencies
Message: Found python3 binary
Message: Getting python install path
Message: Compiling resources
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Message: Compiling resources
Message: Compiling schemas
Program meson_post_install.py found: NO
data/meson.build:12:6: ERROR:  Script or command 'meson_post_install.py' not found or not executable
A full log can be found at /build/com.github.geigi.cozy-0.0.1/debian/build/meson-logs/meson-log.txt
debian/rules:24: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 1
make[1]: Leaving directory '/build/com.github.geigi.cozy-0.0.1'
debian/rules:17: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
E: Failed autobuilding of package
I: unmounting dev/ptmx filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: cleaning the build env 
I: removing directory /var/cache/liftoff-build//7462 and its subdirectories

</details>
### Build Information
Affects Architecture: amd64
Affects Distribution: juno
================================================================================
The command "houston ci --distribution $DIST" exited with 1.
cache.2
store build cache
0.01s1.37snothing changed, not updating cache
Done. Your build exited with 1.
```

**Comment by NathanBnm** [comment]
I'm going to check that.
A bit strange for the post_install.py script

**Comment by NathanBnm** [comment]
Actually I tried to update the `post_install.py` script like this:

```python
#!/usr/bin/env python3
import os
import subprocess

schemadir = os.path.join(os.environ['MESON_INSTALL_PREFIX'], 'share', 'glib-2.0', 'schemas')
iconchachedir = os.path.join(os.environ.get('MESON_INSTALL_PREFIX', '/usr/local'), 'share', 'icons', 'hicolor')

if not os.environ.get('DESTDIR'):
    print('Compiling gsettings schemas…')
    subprocess.call(['glib-compile-schemas', schemadir])

    print('Updating icon cache…')
    subprocess.call(['gtk-update-icon-cache', iconchachedir])
```

But I have this on install:
```bash
Running custom install script '/usr/bin/env python3 /home/nathan/cozy/meson/post_install.py'
Compiling gsettings schemas…
Updating icon cache…
gtk-update-icon-cache: No theme index file.
```

I don't really know what does it means, and I don't really understand how you're installing your icons

**Comment by NathanBnm** [comment]
I really don't understand why he can't find the script when it works perfectly locally.

**Comment by NathanBnm** [comment]
I removed empty translation files :wink:

**Comment by geigi** [comment]
That's really weird... I'll have a look in the next days. Thanks for your work!

**Comment by NathanBnm** [comment]
> That's really weird... I'll have a look in the next days. Thanks for your work!

Yes it is :confused: Feel free to ask if you have any questions.
I hope we'll finally succeed!

**Comment by NathanBnm** [comment]
@geigi As I can say it comes from the debian rules or config, in the debian folder :confused:

**Comment by NathanBnm** [comment]
Finally it seems that's because the `post_install.py` file hasn't the appropriate permission, that's what's was reported here https://github.com/artemanufrij/playmymusic/pull/172#issuecomment-485243829

I'm going to put the debian rules back and make the `post_install.py` file executable :wink:

**Comment by geigi** [comment]
Awesome! Thanks a lot for your work! I only have little time at the moment but i'll merge in the next week or two ;)

**Comment by NathanBnm** [comment]
Hi, any updates here? :smile:

**Comment by geigi** [comment]
I’m sorry, I sadly had absolutely no time for cozy in the last months :( But I’ll test everything next week and then I’ll merge your work. I’m still very greatful for your contribution!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
