### PR TITLE
New branding colors, that look actually good

### LINKED ISSUE #894: AppStream brand color: Use distinct color for dark
The brand color for dark should not be the same as the light one, because it might be used at large sizes where light colors can be disruptive when the rest of the UI is dark. I'd use a darker orange, e.g. `#a44811`.

image

### PR DESCRIPTION
**Pull request by rdbende**
New branding colors, that look actually good. The dark orange is washed-out a bit, but we can't just go with generic purple.

Fixes #894 

rect1

### CODE REVIEW

**Comment by geigi** [comment]
Looks really nice!

**Comment by rdbende** [comment]
Actually, even the old dark mode color looks quite good on Flathub

**Comment by rdbende** [comment]
Uhh, I said nothing.
The dark mode should be fixed:
image

**Comment by geigi** [comment]
But light mode is really nice :)

**Comment by geigi** [comment]
Seems like there is [no way to define a text color yet](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-branding), so we might have to choose another primary color for dark mode...

**Pull request merged**
