### PR TITLE
Basic Opus Support

### PR DESCRIPTION
**Pull request by bmnz90**
no Tag reading

### CODE REVIEW

**Comment by geigi** [comment]
Thanks for your PR. I would like to implement tag reading before including opus support. Are you interested in doing this?

**Comment by bmnz90** [comment]
I will try, my coding skills are somewhat nonexistent ;)

**Comment by geigi** [comment]
Ok cool :)

To get you started:
- You could try using the function `__get_common_tag` before trying out the opus specific ones
- This is the documentation for the opus specific tags: https://mutagen.readthedocs.io/en/latest/api/oggopus.html
- Just have a look on how I implemented this for the other formats
- If you need help let me know!

**Comment by geigi** [comment]
This feature is now included! :)

**Pull request closed without merging**
