### PR TITLE
Icons Redesign 

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon felt a bit too crowded and the headphone also fells "compressed". It also IMO was never really clear what is the object in between the headphone. In this new icon, I made the headphone pretty wide. And, instead of putting the audiobooks cramped between the headphone's cups, I put them behind the headphone.

### CODE REVIEW

**Comment by geigi** [comment]
Awesome, this looks a lot better than the original! Thank you :) Two things that came to my mind:

- We need to comply to the elemetaryOS Guideline for publishing Cozy to the elementaryOS AppCenter. The relevant information is here: https://elementary.io/docs/human-interface-guidelines#iconography Could you have a quick look at it? From my first look everything looks good.
- I have one idea about the icon itself: The headphone-cups (the part that lays on your ears) is smaller than the part which is facing away from the ears. Typically headphones are the other way around (the bigger part on the inside and the smaller part on the outsite, like this example: https://www.jabra.com.de/-/media/Images/Products/Jabra-Move-Style-Edition/Color/titanium_a.png). I think it might look more natural if you try it like this. Would you give it a try?

**Comment by Fatih20** [comment]
Hell yeah I've read that thing. If you read my activity, you'll see I've been making sure the apps at the elementary appcenter comply by it.
Yeah sure, I'll fix the headphone thing.

**Comment by geigi** [comment]
Awesome!

**Comment by geigi** [comment]
I like it a lot! Thank you for your work :)

Liebe Grüße,
Julian

**Comment by Fatih20** [comment]
After you merged the branch, when will the update with the new icon be released?

**Comment by geigi** [comment]
I‘m going to ship the update next week! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fatih20** [comment]
Can you make sure to credit me in the contributors page and the release notes for the update?

**Comment by geigi** [comment]
Of course :) I’m sorry I didn’t ship the update yet... I hope I’ll get it out this week.

**Comment by Fatih20** [comment]
Yo, why is there a black square in the icon? The icon is all transparent.

**Comment by geigi** [comment]
Where are you seeing the black square?

**Comment by Fatih20** [comment]
image

**Comment by geigi** [comment]
Did you create the icon with Inkscape? I had a similar problem sometime ago where I had to export the svg from especially as „non Inkscape svg“ or something like that. I’ll have a look at this tomorrow.

**Comment by Fatih20** [comment]
Yeah, I did use Inkscape. Never happened to me before.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by geigi** [comment]
I fixed the issue. There was an empty flowtext element which some svg renderers cannot display (and render them as a black box). This seems to be the issue with elementaryos. Sadly there are currently some issues with deploying to the App Store (probably cozy only related). I’m in contact with the elementary guys to fix it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geigi** [comment]
It's finally live

**Pull request merged**
