### PR TITLE
Add desktop and appdata files to po/POTFILES

### PR DESCRIPTION
**Pull request by rffontenelle**
This enables translation of info that will be available in places like software centers.

### CODE REVIEW

**Comment by geigi** [comment]
Hey :) Thanks for your PR but I have to decline it because the appdata and desktop file are already translatable using a separate POTFILE: https://github.com/geigi/cozy/blob/master/po/extra/POTFILES

**Comment by geigi** [comment]
Translators are also already translating those files since quite a while. Which App Store did you use to test it?

**Comment by rffontenelle** [comment]
Sorry for the noise. I actually came from [Apps for GNOME](https://world.pages.gitlab.gnome.org/apps-for-gnome) where Cozy's description is in English, but now I see Transifex has a resource for this extra PO and I see cozy translated in GNOME Software. So, I guess "Apps for GNOME" should be adapted somehow to read this extra PO file.

**Comment by geigi** [comment]
No worries :) I see! I don't know if this helps but Cozy is build using the build system meson. During the install step the desktop and appdata file are generated using the translations from the extra resource:
```
desktop_file = i18n.merge_file(
    input: meson.project_name() + '.desktop',
    output: meson.project_name() + '.desktop',
    po_dir: join_paths(meson.source_root(), 'po', 'extra'),
    type: 'desktop',
    install: true,
    install_dir: join_paths(get_option('datadir'), 'applications')
)

appstream_file = i18n.merge_file(
    input: meson.project_name() + '.appdata.xml',
    output: meson.project_name() + '.appdata.xml',
    po_dir: join_paths(meson.source_root(), 'po', 'extra'),
    install: true,
    install_dir: join_paths(get_option('datadir'), 'metainfo')
)
```

But Apps for GNOME propably gathers all information from the repo without building the app?

**Comment by geigi** [comment]
Just tested it with German and Italian and the translations worked fine in Apps for Gnome, maybe your language has no translation yet?

**Comment by rffontenelle** [comment]
It seems to be translated in my language (pt_BR) in GNOME Software, but not in (Apps for GNOME in pt_BR]

**Comment by geigi** [comment]
Oh I found the issue... pt_BR is missing from the extra LINGUAS file... I'll fix it right now. I also plan to release in the next few days when more translations have arrived, then it should be fixed everywhere else (hopefully) :)

**Comment by rffontenelle** [comment]
Hey, just to mention that adding pt_BR to extra LINGUAS file solved the issue. I can see it translated in [Apps for GNOME](https://world.pages.gitlab.gnome.org/apps-for-gnome/pt_BR/):

Captura de tela de 2021-08-23 10-11-32

Thanks!

**Pull request closed without merging**
