### PR TITLE
the update is tied to the file checksum

### PR DESCRIPTION
**Pull request by oleg-krv**
It is more correct to look at the file checksum for making changes to the database

### CODE REVIEW

**Comment by geigi** [comment]
Do you think this is necessary? The modified date should represent this already at a lower cost when reimporting. But it may cause problems on systems with messed up time...
I tried to test the code but I think you forgot to import binascii:
`WARNING:importer:name 'binascii' is not defined`

**Comment by oleg-krv** [comment]
Sorry. I definitely forgot to add the import.
Snap to the date faster, but not always accurately allows you to determine the file change, or vice versa cause a false alarm.
crc32 - slower, but import occurs when the user controls. A slight slowdown will not affect usability, but give greater accuracy.

**Comment by geigi** [comment]
Thanks for fixing ;) So I tested this with my audiobooks on my network storage. The reimport over wifi is now really slow (but doing this over wifi isn't a great idea anyway). 
The check reads every file completely? So when I have 50GB of audiobooks they have to be completely read?

**Comment by oleg-krv** [comment]
I did not think about network folders.
as a suggestion:
1) for a general scan, only search for new files
2) make an option - update the book. If I changed the tags in a book, I do not need to re-scan the entire library.
Or to make a choice of books in the library - and for them a group rescanning.

**Comment by geigi** [comment]
Good idea, I will definitely add a separate refresh option for the books at some time via a right click menu. There will be other stuff also like open in file manager...
How about making crc32 as an option for now in the app settings so the user can choose between speed and accuracy?

**Comment by oleg-krv** [comment]
Ok. It will be great.
I'm now testing the display of the duration of the book and the current position.
It remains to do a little cleanup and optimizations and lay out this patch

**Comment by oleg-krv** [comment]
I checked it on a network drive: it slows down the search for books very much.
I have an idea:
- In the requests there is a desire to be able to specify several folders for books. You can specify the folder type: network, local. They use different ways to update. And also it will be possible to implement copying of the book into a local folder (this is actual on the laptop for offline reading) and the ability to upload to a network folder for storage.
But this is so: my fantasies :)

PS: Flight of fantasy: the history of already read books with the ability to make notes about books :), The history of the book is not deleted when you delete a book from the disc, but it is possible to add a book already read (listened) on the phone

**Comment by geigi** [comment]
Awesome! I really like your ideas! Especially that you can sync books from your network drive for offline use. On the todo list :) The note feature would be also nice to have :)

**Comment by geigi** [comment]
I've just pushed the crc32 implementation on the master branch But I noticed an issue: The __crc32_from_file function copys the entire file into memory before it calculates the checksum. This can be problematic as some may have audiobooks that are one file only several GB of size. Do you have an idea how to fix the crc function?

**Comment by geigi** [comment]
I just found a solution, I push it after testing

**Pull request closed without merging**
