### PR TITLE
add compability for peewee 3

### PR DESCRIPTION
**Pull request by jnbr**
changes are small but not backwards compatible to peewee < 3.0

### CODE REVIEW

**Comment by geigi** [comment]
Thanks :) We definitely need backwards compatibility as most distros don't have peewee 3 in their repositories yet. Is peewee3 an additional package in your distro or is it an update?

**Comment by jnbr** [comment]
I would prefer to do this as an update and not as separate package. It is only packaged in Voidlinux because of cozy.

**Comment by jnbr** [comment]
yes

**Comment by jnbr** [comment]
I added a commit to stay compatible with peewee 2.

**Comment by geigi** [comment]
That's cool :)
Thanks a lot!

**Pull request merged**
